kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "AmazonRoute53-ingress-controller.name" . }}
rules:
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions"]
    resources:
      - ingresses
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["get", "list", "watch"]
